[package]
name = "report_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
rand = "0.9.1"
postcard = { version = "1.1.3", features = ["use-std"] }
shared = { path = "../shared" }
